[package]
name = "nomr"
version = "0.1.0"
authors = ["Tobias Kunze <r@rixx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
structopt = "0.2.10"
